### PR TITLE
Refactor Polarion reporting

### PR DESCRIPTION
**Pull request by MaxBab**
Convert existing bash script of polarion report to python script.
- Generate testcases and testrun report out of junit files.
- Add support for cypress junit files.
- Push reports to polarion.
- Query reports status from polarion.

### CODE REVIEW

**Review by manosnoam — APPROVED** [review]
Looks good.
Any reason not to use https://pypi.org/project/polarion/ ?

Can you add a link to test run creation example, and validate that it also handle modifying existing test runs?

**Comment by MaxBab** [comment]
@manosnoam 

> Looks good. Any reason not to use https://pypi.org/project/polarion/ ?
As you might see, the script is pretty simple.
I didn't want to overload everything with a lot of dependencies.

> Can you add a link to test run creation example, and validate that it also handle modifying existing test runs?
Sure.
These are the updated test runs:
https://polarion.engineering.redhat.com/polarion/#/project/RHACM4K/testrun?id=multi-cluster-networking_acm-2-7-0-submariner-0-14-1-aro-gcp-globalnet
https://polarion.engineering.redhat.com/polarion/#/project/RHACM4K/testrun?id=multi-cluster-networking_acm-2-7-0-submariner-0-14-1-aro-vsphere-globalnet
https://polarion.engineering.redhat.com/polarion/#/project/RHACM4K/testrun?id=multi-cluster-networking_acm-2-7-0-submariner-0-14-1-aro-azure-globalnet

**Pull request merged**
